### ISSUE TITLE
Can't run the test suite

### ISSUE THREAD

**Issue by moonglum** [tgpfeiffer/restful-openerp#15]
After setting up everything as described in the README, i can't run the test suite with `trial basicTests`. I get the following error:

```
basicTests ...                                                          [ERROR]

===============================================================================
[ERROR]
Traceback (most recent call last):
  File "/tmp/restful-openerp/.env/local/lib/python2.7/site-packages/twisted/trial/runner.py", line 660, in loadByNames
    things.append(self.findByName(name))
  File "/tmp/restful-openerp/.env/local/lib/python2.7/site-packages/twisted/trial/runner.py", line 470, in findByName
    return reflect.namedAny(name)
  File "/tmp/restful-openerp/.env/local/lib/python2.7/site-packages/twisted/python/reflect.py", line 469, in namedAny
    raise ModuleNotFound("No module named %r" % (name,))
twisted.python.reflect.ModuleNotFound: No module named 'basicTests'

basicTests
-------------------------------------------------------------------------------
Ran 1 tests in 0.015s

FAILED (errors=1)
```

* Version of restful-openerp: Current one (Commit 635e01a2637fc932e846b3edcd88eed2e0e59af4), just pulled it
* Python Version: 2.7.6
*  OpenERP version: 8.0
* Operating System: Ubuntu 14.04

**Comment by tgpfeiffer** [comment]
This is a very good question, and I wonder when `trial basicTests` has ever worked... ;-) It seems like you need

    trial tests.GetTests
    trial tests.PostTests
    trial tests.PutTests

to run all the tests (and need to set access credentials in `restful-openerp.cfg`.

**Comment by tgpfeiffer** [comment]
(Closing because no response for some months.)
