### ISSUE TITLE
help to install depencies

### ISSUE THREAD

**Issue by jeanlucDjeke** [tgpfeiffer/restful-openerp#16]
Hello, i'm a new developer in odoo.I have to develop a restFul api to communicate with my odoo in backend.
I see this post and i'm very interested but i can't install the depencies.Please help me
soory my english is not very good

**Comment by tgpfeiffer** [comment]
First, I don't know if this software still works with Odoo in the current versions. I am running it only against OpenERP 6.

As for the dependency installation, did you follow the instructions from the Readme?
> `virtualenv --no-site-packages .env`
> `. .env/bin/activate`
> `pip install -r requirements.txt`

**Comment by tgpfeiffer** [comment]
(Closing because no response for some months.)
