### ISSUE TITLE
Connection was refused by other side: 111

### ISSUE THREAD

**Issue by TempWord** [tgpfeiffer/restful-openerp#17]
Hi all, 

Is this error is only due to the fact that I am in Odoo 8 environement ?

The database is on PostgreSQL 9.3.11;
Thanks in advance!

**Comment by tgpfeiffer** [comment]
> Connection was refused by other side: 111

Where/when do you get this error message? If this happens between restful-openerp and Odoo, it may be that there is a firewall active, XML-RPC service is not enabled, or the host/port settings are not correct in the config file.

**Comment by tgpfeiffer** [comment]
(Closing because no response for some months.)
