### ISSUE TITLE
How I use this module

### ISSUE THREAD

**Issue by Asmaa-Aly** [tgpfeiffer/restful-openerp#19]
Just question i want to know how i can use it to help me integration with .net application

**Comment by tgpfeiffer** [comment]
This is not a module, it is a proxy server. It runs between your application and your OpenERP instance:

    Your App --[HTTP/REST]--> restful-openerp --[HTTP/XML-RPC]--> OpenERP

The readme describes how to set this software up and how to configure it.

**Comment by Asmaa-Aly** [comment]
ok, thank you :)
